var data = {
  userInfo: {
    avatarUrl: 'http://out2ei6gm.bkt.clouddn.com/position.jpg',
    nickName: '会收钱用户'
  },
  _getUserInfo: false,
  _onshow: false,
  userData: {
    user: {
      headerimg: ''
    }
  },
  _rank: '',
  _name: '',
  _show: '',
  hasMsg: 0,
  userCost: 0,
  sellerCost: 0,
  singup: false,
  firstShow: true,
  uplevel: [{
    value: 1,
    text: '铜币'
  }, {
    value: 2,
    text: '银元'
  }, {
    value: 3,
    text: '金砖'
  }],
  uplevelIndex: 0,
  // 我的
  category: [{
    class: 'icon-hhq_wode_xingyundou',
    color: '#52d4ff',
    text: '幸运豆',
    point: '0.00',
    url: 'luckBean'
  }, {
    class: 'icon-jifen',
    color: '#ffb80d',
    text: '积分',
    point: '0.00',
    url: 'point'
  }, {
    class: 'icon-shouyiqingkuang',
    color: '#09b83f',
    text: '可提现收益',
    point: '   ',
    url: 'profit'
  }, {
    class: 'icon-jifen1',
    color: '#f92c1a',
    text: '推荐客户赚积分',
    url: 'QRcode',
    type: '01'
  }, {
    class: 'icon-wodehaoyou',
    color: '#10c4ff',
    text: '我的客户',
    url: 'myCustomer'
  }, {}],
  // 商户功能
  storeItems: [{
    class: 'icon-fazhankehu',
    color: '#ffbc1c',
    text: '发展客户',
    url: 'QRcode',
    type: '01'
  }, {
    class: 'icon-shoukuanma',
    color: '#0f86ff',
    text: '收款码',
    url: ''
  }, {}],
  // 代理功能
  agentItems: [{
    class: 'icon-fazhandaili',
    color: '#bf1539',
    text: '发展代理',
    url: 'QRcode',
    type: '02'
  }, {
    class: 'icon-fazhanshanghu',
    color: '#04bbf7',
    text: '发展商户',
    url: 'QRcode',
    type: '03'
  }, {
    class: 'icon-daili',
    color: '#1AF98D',
    text: '购买代理',
    url: 'agentQuota'
  }, {
    class: 'icon-wodedaili',
    color: '#bf1539',
    text: '我的代理',
    url: 'myAgent'
  }, {
    class: 'icon-wodeshanghu',
    color: '#04bbf7',
    text: '我的商户',
    url: 'myAgentStore'
  }, {
    class: 'icon-hhq_wode_kaitongdail',
    color: '#1AF98D',
    text: '开通代理',
    url: 'agentOpen'
  }]
}

module.exports = data
